import rus from "./assets/rus-flag.png";
import est from "./assets/est-flag.png";
import por from "./assets/por-flag.png";
import isr from "./assets/isr-flag.png";
import pol from "./assets/pol-flag.png";
import ned from "./assets/ned-flag.png";
import eng from "./assets/eng-flag.png";

const results = [
  {
    id: 1,
    rank: 1,
    flag_img: rus,
    team: "RUS",
    bib: 212,
    name: "Bonartsev Aleksandr",
    d: 43.833,
    e: 43.833,
    pen: 43.833,
    total: 102.256,
    genderCategory: "MAG",
    round: "Final",
    competitionType: "Apparatus",
    ageCategory: "Seniors",
  },
  {
    id: 2,
    rank: 2,
    flag_img: est,
    team: "EST",
    bib: 132,
    name: "Bonartsev Aleksandr",
    d: 43.833,
    e: 43.833,
    pen: 43.833,
    total: 102.256,
    genderCategory: "MAG",
    round: "Final",
    competitionType: "Apparatus",
    ageCategory: "Seniors",
  },
  {
    id: 3,
    rank: 3,
    flag_img: por,
    team: "POR",
    bib: 624,
    name: "Bonartsev Aleksandr",
    d: 43.833,
    e: 43.833,
    pen: 43.833,
    total: 102.256,
    genderCategory: "MAG",
    round: "Final",
    competitionType: "Apparatus",
    ageCategory: "Seniors",
  },
  {
    id: 4,
    rank: 4,
    flag_img: isr,
    team: "ISR",
    bib: 212,
    name: "Bonartsev Aleksandr",
    d: 43.833,
    e: 43.833,
    pen: 43.833,
    total: 102.256,
    genderCategory: "MAG",
    round: "Final",
    competitionType: "Apparatus",
    ageCategory: "Seniors",
  },
  {
    id: 5,
    rank: 5,
    flag_img: pol,
    team: "POL",
    bib: 401,
    name: "Bonartsev Aleksandr",
    d: 43.833,
    e: 43.833,
    pen: 43.833,
    total: 102.256,
    genderCategory: "MAG",
    round: "Final",
    competitionType: "Apparatus",
    ageCategory: "Seniors",
  },
  {
    id: 6,
    rank: 6,
    flag_img: ned,
    team: "RUS",
    bib: 102,
    name: "Bonartsev Aleksandr",
    d: 43.833,
    e: 43.833,
    pen: 43.833,
    total: 102.256,
    genderCategory: "MAG",
    round: "Final",
    competitionType: "Apparatus",
    ageCategory: "Seniors",
  },
  {
    id: 7,
    rank: 7,
    flag_img: eng,
    team: "GBR",
    bib: 102,
    name: "Bonartsev Aleksandr",
    d: 43.833,
    e: 43.833,
    pen: 43.833,
    total: 102.256,
    genderCategory: "MAG",
    round: "Final",
    competitionType: "Apparatus",
    ageCategory: "Seniors",
  },
  {
    id: 8,
    rank: 8,
    flag_img: eng,
    team: "GBR",
    bib: 102,
    name: "Bonartsev Aleksandr",
    d: 43.833,
    e: 43.833,
    pen: 43.833,
    total: 102.256,
    genderCategory: "MAG",
    round: "Qualification",
    competitionType: "Apparatus",
    ageCategory: "Juniors",
  },
  {
    id: 9,
    rank: 9,
    flag_img: eng,
    team: "GBR",
    bib: 102,
    name: "Bonartsev Aleksandr",
    d: 43.833,
    e: 43.833,
    pen: 43.833,
    total: 102.256,
    genderCategory: "MAG",
    round: "Qualification",
    competitionType: "Apparatus",
    ageCategory: "Juniors",
  },
  {
    id: 10,
    rank: 10,
    flag_img: eng,
    team: "GBR",
    bib: 102,
    name: "Bonartsev Aleksandr",
    d: 43.833,
    e: 43.833,
    pen: 43.833,
    total: 102.256,
    genderCategory: "MAG",
    round: "Qualification",
    competitionType: "Apparatus",
    ageCategory: "Juniors",
  },
  {
    id: 11,
    rank: 11,
    flag_img: eng,
    team: "GBR",
    bib: 102,
    name: "Bonartsev Aleksandr",
    d: 43.833,
    e: 43.833,
    pen: 43.833,
    total: 102.256,
    genderCategory: "MAG",
    round: "Qualification",
    competitionType: "Apparatus",
    ageCategory: "Juniors",
  },
  {
    id: 12,
    rank: 12,
    flag_img: eng,
    team: "GBR",
    bib: 102,
    name: "Bonartsev Aleksandr",
    d: 43.833,
    e: 43.833,
    pen: 43.833,
    total: 102.256,
    genderCategory: "MAG",
    round: "Qualification",
    competitionType: "Apparatus",
    ageCategory: "Juniors",
  },
];

export default results;